before_script:
  - echo $(uname -a)
  - wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-linux-x64.tar.gz
  - tar -zxf jdk-8u92-linux-x64.tar.gz -C /opt/jdk
  - update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_92/bin/java 100
  - update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_92/bin/javac 100
  - java -version
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar --extract --gzip --file=android-sdk.tgz
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-22.0.1,android-22,extra-android-m2repository
  - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/gradle-2.12-bin.zip
  - unzip -q gradle.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux

test:
  script:
    - gradle-2.12/bin/gradle build